FROM golang:1.23

WORKDIR /usr/src/app

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .
RUN go build -o /server/rms_proxy 

ENV RMS_FILE_FILES_FRONT=/front


CMD ["/server/rms_proxy"]
